# resolve-type-names: false

module ::Magic
  class ::Magic::Tag < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Magic::Tag, ::Magic::Tag::ActiveRecord_Relation, ::Integer]

    module ::Magic::Tag::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def name: () -> ::String

      def name=: (::String) -> ::String

      def name?: () -> bool

      def name_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def name_change: () -> [ ::String?, ::String? ]

      def name_will_change!: () -> void

      def name_was: () -> ::String?

      def name_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def name_previous_change: () -> ::Array[::String?]?

      def name_previously_was: () -> ::String?

      def name_before_last_save: () -> ::String?

      def name_change_to_be_saved: () -> ::Array[::String?]?

      def name_in_database: () -> ::String?

      def saved_change_to_name: () -> ::Array[::String?]?

      def saved_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_name?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_name!: () -> void

      def clear_name_change: () -> void

      def name_before_type_cast: () -> ::String

      def name_for_database: () -> ::String

      def concept_id: () -> ::Integer?

      def concept_id=: (::Integer?) -> ::Integer?

      def concept_id?: () -> bool

      def concept_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def concept_id_change: () -> [ ::Integer?, ::Integer? ]

      def concept_id_will_change!: () -> void

      def concept_id_was: () -> ::Integer?

      def concept_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def concept_id_previous_change: () -> ::Array[::Integer?]?

      def concept_id_previously_was: () -> ::Integer?

      def concept_id_before_last_save: () -> ::Integer?

      def concept_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def concept_id_in_database: () -> ::Integer?

      def saved_change_to_concept_id: () -> ::Array[::Integer?]?

      def saved_change_to_concept_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_concept_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_concept_id!: () -> void

      def clear_concept_id_change: () -> void

      def concept_id_before_type_cast: () -> ::Integer?

      def concept_id_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time
    end
    include ::Magic::Tag::GeneratedAttributeMethods
    module ::Magic::Tag::GeneratedAliasAttributeMethods
      include ::Magic::Tag::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Magic::Tag::GeneratedAliasAttributeMethods
    def taggings: () -> ::Magic::Tagging::ActiveRecord_Associations_CollectionProxy
    def taggings=: (::Magic::Tagging::ActiveRecord_Associations_CollectionProxy | ::Array[::Magic::Tagging]) -> (::Magic::Tagging::ActiveRecord_Associations_CollectionProxy | ::Array[::Magic::Tagging])
    def tagging_ids: () -> ::Array[::Integer]
    def tagging_ids=: (::Array[::Integer]) -> ::Array[::Integer]

    def concept: () -> ::Catalog::Concept?
    def concept=: (::Catalog::Concept?) -> ::Catalog::Concept?
    def reload_concept: () -> ::Catalog::Concept?
    def build_concept: (?untyped) -> ::Catalog::Concept
    def create_concept: (?untyped) -> ::Catalog::Concept
    def create_concept!: (?untyped) -> ::Catalog::Concept

    module ::Magic::Tag::GeneratedAssociationMethods
    end
    include ::Magic::Tag::GeneratedAssociationMethods

    module ::Magic::Tag::GeneratedRelationMethods
    end

    class ::Magic::Tag::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Magic::Tag]
      include ::Magic::Tag::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Magic::Tag, ::Integer]
    end

    class ::Magic::Tag::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Magic::Tag]
      include ::Magic::Tag::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Magic::Tag, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Magic::Tag
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Magic::Tag]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Magic::Tag
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Magic::Tag]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Magic::Tag
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Magic::Tag]
      def reload: () -> ::Array[::Magic::Tag]

      def replace: (::Array[::Magic::Tag]) -> void
      def delete: (*::Magic::Tag | ::Integer) -> ::Array[::Magic::Tag]
      def destroy: (*::Magic::Tag | ::Integer) -> ::Array[::Magic::Tag]
      def <<: (*::Magic::Tag | ::Array[::Magic::Tag]) -> self
      def prepend: (*::Magic::Tag | ::Array[::Magic::Tag]) -> self
    end
  end
end

module ::Magic
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Magic::Tagging < ::ApplicationRecord
end
class ::Magic::Tagging::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Catalog::Concept < ::ApplicationRecord
end
module ::Catalog
end
