# resolve-type-names: false

module ::Copyright
  class ::Copyright::ClearancePublishing < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Copyright::ClearancePublishing, ::Copyright::ClearancePublishing::ActiveRecord_Relation, ::Integer]

    module ::Copyright::ClearancePublishing::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def clearance_id: () -> ::Integer

      def clearance_id=: (::Integer) -> ::Integer

      def clearance_id?: () -> bool

      def clearance_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def clearance_id_change: () -> [ ::Integer?, ::Integer? ]

      def clearance_id_will_change!: () -> void

      def clearance_id_was: () -> ::Integer?

      def clearance_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def clearance_id_previous_change: () -> ::Array[::Integer?]?

      def clearance_id_previously_was: () -> ::Integer?

      def clearance_id_before_last_save: () -> ::Integer?

      def clearance_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def clearance_id_in_database: () -> ::Integer?

      def saved_change_to_clearance_id: () -> ::Array[::Integer?]?

      def saved_change_to_clearance_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_clearance_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_clearance_id!: () -> void

      def clear_clearance_id_change: () -> void

      def clearance_id_before_type_cast: () -> ::Integer

      def clearance_id_for_database: () -> ::Integer

      def position: () -> ::Integer?

      def position=: (::Integer?) -> ::Integer?

      def position?: () -> bool

      def position_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def position_change: () -> [ ::Integer?, ::Integer? ]

      def position_will_change!: () -> void

      def position_was: () -> ::Integer?

      def position_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def position_previous_change: () -> ::Array[::Integer?]?

      def position_previously_was: () -> ::Integer?

      def position_before_last_save: () -> ::Integer?

      def position_change_to_be_saved: () -> ::Array[::Integer?]?

      def position_in_database: () -> ::Integer?

      def saved_change_to_position: () -> ::Array[::Integer?]?

      def saved_change_to_position?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_position?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_position!: () -> void

      def clear_position_change: () -> void

      def position_before_type_cast: () -> ::Integer?

      def position_for_database: () -> ::Integer?

      def year: () -> ::String?

      def year=: (::String?) -> ::String?

      def year?: () -> bool

      def year_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def year_change: () -> [ ::String?, ::String? ]

      def year_will_change!: () -> void

      def year_was: () -> ::String?

      def year_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def year_previous_change: () -> ::Array[::String?]?

      def year_previously_was: () -> ::String?

      def year_before_last_save: () -> ::String?

      def year_change_to_be_saved: () -> ::Array[::String?]?

      def year_in_database: () -> ::String?

      def saved_change_to_year: () -> ::Array[::String?]?

      def saved_change_to_year?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_year?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_year!: () -> void

      def clear_year_change: () -> void

      def year_before_type_cast: () -> ::String?

      def year_for_database: () -> ::String?

      def kind: () -> ::String

      def kind=: (::String | ::Symbol) -> ::String

      def kind?: () -> bool

      def kind_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def kind_change: () -> [ ::String?, ::String? ]

      def kind_will_change!: () -> void

      def kind_was: () -> ::String?

      def kind_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def kind_previous_change: () -> ::Array[::String?]?

      def kind_previously_was: () -> ::String?

      def kind_before_last_save: () -> ::String?

      def kind_change_to_be_saved: () -> ::Array[::String?]?

      def kind_in_database: () -> ::String?

      def saved_change_to_kind: () -> ::Array[::String?]?

      def saved_change_to_kind?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_kind?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_kind!: () -> void

      def clear_kind_change: () -> void

      def kind_before_type_cast: () -> ::String

      def kind_for_database: () -> ::String

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time
    end
    include ::Copyright::ClearancePublishing::GeneratedAttributeMethods
    module ::Copyright::ClearancePublishing::GeneratedAliasAttributeMethods
      include ::Copyright::ClearancePublishing::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Copyright::ClearancePublishing::GeneratedAliasAttributeMethods

    def clearance: () -> ::Copyright::Clearance
    def clearance=: (::Copyright::Clearance?) -> ::Copyright::Clearance?
    def reload_clearance: () -> ::Copyright::Clearance?
    def build_clearance: (?untyped) -> ::Copyright::Clearance
    def create_clearance: (?untyped) -> ::Copyright::Clearance
    def create_clearance!: (?untyped) -> ::Copyright::Clearance

    module ::Copyright::ClearancePublishing::GeneratedAssociationMethods
    end
    include ::Copyright::ClearancePublishing::GeneratedAssociationMethods

    def copyright_notice!: () -> bool
    def copyright_notice?: () -> bool
    def no_copyright_notice!: () -> bool
    def no_copyright_notice?: () -> bool
    def reprint_or_facsimile!: () -> bool
    def reprint_or_facsimile?: () -> bool
    def self.kinds: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
    def self.copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    def self.not_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    def self.no_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    def self.not_no_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    def self.reprint_or_facsimile: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    def self.not_reprint_or_facsimile: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

    module ::Copyright::ClearancePublishing::GeneratedRelationMethods
      def kinds: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

      def copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

      def not_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

      def no_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

      def not_no_copyright_notice: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

      def reprint_or_facsimile: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation

      def not_reprint_or_facsimile: () -> ::Copyright::ClearancePublishing::ActiveRecord_Relation
    end

    class ::Copyright::ClearancePublishing::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Copyright::ClearancePublishing]
      include ::Copyright::ClearancePublishing::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Copyright::ClearancePublishing, ::Integer]
    end

    class ::Copyright::ClearancePublishing::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Copyright::ClearancePublishing]
      include ::Copyright::ClearancePublishing::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Copyright::ClearancePublishing, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::ClearancePublishing
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::ClearancePublishing]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::ClearancePublishing
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::ClearancePublishing]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::ClearancePublishing
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::ClearancePublishing]
      def reload: () -> ::Array[::Copyright::ClearancePublishing]

      def replace: (::Array[::Copyright::ClearancePublishing]) -> void
      def delete: (*::Copyright::ClearancePublishing | ::Integer) -> ::Array[::Copyright::ClearancePublishing]
      def destroy: (*::Copyright::ClearancePublishing | ::Integer) -> ::Array[::Copyright::ClearancePublishing]
      def <<: (*::Copyright::ClearancePublishing | ::Array[::Copyright::ClearancePublishing]) -> self
      def prepend: (*::Copyright::ClearancePublishing | ::Array[::Copyright::ClearancePublishing]) -> self
    end
  end
end

module ::Copyright
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Copyright::Clearance < ::ApplicationRecord
end
