# resolve-type-names: false

module ::Copyright
  class ::Copyright::Finding < ::ApplicationRecord
    extend ::ActiveRecord::Base::ClassMethods[::Copyright::Finding, ::Copyright::Finding::ActiveRecord_Relation, ::Integer]

    module ::Copyright::Finding::GeneratedAttributeMethods
      def id: () -> ::Integer

      def id=: (::Integer) -> ::Integer

      def id?: () -> bool

      def id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_change: () -> [ ::Integer?, ::Integer? ]

      def id_will_change!: () -> void

      def id_was: () -> ::Integer?

      def id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def id_previous_change: () -> ::Array[::Integer?]?

      def id_previously_was: () -> ::Integer?

      def id_before_last_save: () -> ::Integer?

      def id_change_to_be_saved: () -> ::Array[::Integer?]?

      def id_in_database: () -> ::Integer?

      def saved_change_to_id: () -> ::Array[::Integer?]?

      def saved_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_id!: () -> void

      def clear_id_change: () -> void

      def id_before_type_cast: () -> ::Integer

      def id_for_database: () -> ::Integer

      def investigation_id: () -> ::Integer

      def investigation_id=: (::Integer) -> ::Integer

      def investigation_id?: () -> bool

      def investigation_id_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def investigation_id_change: () -> [ ::Integer?, ::Integer? ]

      def investigation_id_will_change!: () -> void

      def investigation_id_was: () -> ::Integer?

      def investigation_id_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def investigation_id_previous_change: () -> ::Array[::Integer?]?

      def investigation_id_previously_was: () -> ::Integer?

      def investigation_id_before_last_save: () -> ::Integer?

      def investigation_id_change_to_be_saved: () -> ::Array[::Integer?]?

      def investigation_id_in_database: () -> ::Integer?

      def saved_change_to_investigation_id: () -> ::Array[::Integer?]?

      def saved_change_to_investigation_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_investigation_id?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_investigation_id!: () -> void

      def clear_investigation_id_change: () -> void

      def investigation_id_before_type_cast: () -> ::Integer

      def investigation_id_for_database: () -> ::Integer

      def section: () -> ::String

      def section=: (::String | ::Symbol) -> ::String

      def section?: () -> bool

      def section_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def section_change: () -> [ ::String?, ::String? ]

      def section_will_change!: () -> void

      def section_was: () -> ::String?

      def section_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def section_previous_change: () -> ::Array[::String?]?

      def section_previously_was: () -> ::String?

      def section_before_last_save: () -> ::String?

      def section_change_to_be_saved: () -> ::Array[::String?]?

      def section_in_database: () -> ::String?

      def saved_change_to_section: () -> ::Array[::String?]?

      def saved_change_to_section?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_section?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_section!: () -> void

      def clear_section_change: () -> void

      def section_before_type_cast: () -> ::String

      def section_for_database: () -> ::String

      def question: () -> ::String?

      def question=: (::String?) -> ::String?

      def question?: () -> bool

      def question_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def question_change: () -> [ ::String?, ::String? ]

      def question_will_change!: () -> void

      def question_was: () -> ::String?

      def question_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def question_previous_change: () -> ::Array[::String?]?

      def question_previously_was: () -> ::String?

      def question_before_last_save: () -> ::String?

      def question_change_to_be_saved: () -> ::Array[::String?]?

      def question_in_database: () -> ::String?

      def saved_change_to_question: () -> ::Array[::String?]?

      def saved_change_to_question?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_question?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_question!: () -> void

      def clear_question_change: () -> void

      def question_before_type_cast: () -> ::String?

      def question_for_database: () -> ::String?

      def answer: () -> ::String?

      def answer=: (::String?) -> ::String?

      def answer?: () -> bool

      def answer_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def answer_change: () -> [ ::String?, ::String? ]

      def answer_will_change!: () -> void

      def answer_was: () -> ::String?

      def answer_previously_changed?: (?from: ::String?, ?to: ::String?) -> bool

      def answer_previous_change: () -> ::Array[::String?]?

      def answer_previously_was: () -> ::String?

      def answer_before_last_save: () -> ::String?

      def answer_change_to_be_saved: () -> ::Array[::String?]?

      def answer_in_database: () -> ::String?

      def saved_change_to_answer: () -> ::Array[::String?]?

      def saved_change_to_answer?: (?from: ::String?, ?to: ::String?) -> bool

      def will_save_change_to_answer?: (?from: ::String?, ?to: ::String?) -> bool

      def restore_answer!: () -> void

      def clear_answer_change: () -> void

      def answer_before_type_cast: () -> ::String?

      def answer_for_database: () -> ::String?

      def position: () -> ::Integer?

      def position=: (::Integer?) -> ::Integer?

      def position?: () -> bool

      def position_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def position_change: () -> [ ::Integer?, ::Integer? ]

      def position_will_change!: () -> void

      def position_was: () -> ::Integer?

      def position_previously_changed?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def position_previous_change: () -> ::Array[::Integer?]?

      def position_previously_was: () -> ::Integer?

      def position_before_last_save: () -> ::Integer?

      def position_change_to_be_saved: () -> ::Array[::Integer?]?

      def position_in_database: () -> ::Integer?

      def saved_change_to_position: () -> ::Array[::Integer?]?

      def saved_change_to_position?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def will_save_change_to_position?: (?from: ::Integer?, ?to: ::Integer?) -> bool

      def restore_position!: () -> void

      def clear_position_change: () -> void

      def position_before_type_cast: () -> ::Integer?

      def position_for_database: () -> ::Integer?

      def created_at: () -> ::ActiveSupport::TimeWithZone

      def created_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def created_at?: () -> bool

      def created_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def created_at_will_change!: () -> void

      def created_at_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def created_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def created_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def created_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def created_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_created_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_created_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_created_at!: () -> void

      def clear_created_at_change: () -> void

      def created_at_before_type_cast: () -> ::Time

      def created_at_for_database: () -> ::Time

      def updated_at: () -> ::ActiveSupport::TimeWithZone

      def updated_at=: (::ActiveSupport::TimeWithZone) -> ::ActiveSupport::TimeWithZone

      def updated_at?: () -> bool

      def updated_at_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_change: () -> [ ::ActiveSupport::TimeWithZone?, ::ActiveSupport::TimeWithZone? ]

      def updated_at_will_change!: () -> void

      def updated_at_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_previously_changed?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def updated_at_previous_change: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_previously_was: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_before_last_save: () -> ::ActiveSupport::TimeWithZone?

      def updated_at_change_to_be_saved: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def updated_at_in_database: () -> ::ActiveSupport::TimeWithZone?

      def saved_change_to_updated_at: () -> ::Array[::ActiveSupport::TimeWithZone?]?

      def saved_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def will_save_change_to_updated_at?: (?from: ::ActiveSupport::TimeWithZone?, ?to: ::ActiveSupport::TimeWithZone?) -> bool

      def restore_updated_at!: () -> void

      def clear_updated_at_change: () -> void

      def updated_at_before_type_cast: () -> ::Time

      def updated_at_for_database: () -> ::Time
    end
    include ::Copyright::Finding::GeneratedAttributeMethods
    module ::Copyright::Finding::GeneratedAliasAttributeMethods
      include ::Copyright::Finding::GeneratedAttributeMethods

      alias id_value id

      alias id_value= id=

      alias id_value? id?

      alias id_value_changed? id_changed?

      alias id_value_change id_change

      alias id_value_will_change! id_will_change!

      alias id_value_was id_was

      alias id_value_previously_changed? id_previously_changed?

      alias id_value_previous_change id_previous_change

      alias id_value_previously_was id_previously_was

      alias id_value_before_last_save id_before_last_save

      alias id_value_change_to_be_saved id_change_to_be_saved

      alias id_value_in_database id_in_database

      alias saved_change_to_id_value saved_change_to_id

      alias saved_change_to_id_value? saved_change_to_id?

      alias will_save_change_to_id_value? will_save_change_to_id?

      alias restore_id_value! restore_id!

      alias clear_id_value_change clear_id_change

      alias id_value_before_type_cast id_before_type_cast

      alias id_value_for_database id_for_database
    end
    include ::Copyright::Finding::GeneratedAliasAttributeMethods
    def citations: () -> ::Copyright::Citation::ActiveRecord_Associations_CollectionProxy
    def citations=: (::Copyright::Citation::ActiveRecord_Associations_CollectionProxy | ::Array[::Copyright::Citation]) -> (::Copyright::Citation::ActiveRecord_Associations_CollectionProxy | ::Array[::Copyright::Citation])
    def citation_ids: () -> ::Array[::Integer]
    def citation_ids=: (::Array[::Integer]) -> ::Array[::Integer]

    def investigation: () -> ::Copyright::Investigation
    def investigation=: (::Copyright::Investigation?) -> ::Copyright::Investigation?
    def reload_investigation: () -> ::Copyright::Investigation?
    def build_investigation: (?untyped) -> ::Copyright::Investigation
    def create_investigation: (?untyped) -> ::Copyright::Investigation
    def create_investigation!: (?untyped) -> ::Copyright::Investigation

    module ::Copyright::Finding::GeneratedAssociationMethods
    end
    include ::Copyright::Finding::GeneratedAssociationMethods

    def basic!: () -> bool
    def basic?: () -> bool
    def biographical!: () -> bool
    def biographical?: () -> bool
    def bibliographical!: () -> bool
    def bibliographical?: () -> bool
    def renewal!: () -> bool
    def renewal?: () -> bool
    def self.sections: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]
    def self.basic: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.not_basic: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.biographical: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.not_biographical: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.bibliographical: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.not_bibliographical: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.renewal: () -> ::Copyright::Finding::ActiveRecord_Relation
    def self.not_renewal: () -> ::Copyright::Finding::ActiveRecord_Relation

    module ::Copyright::Finding::GeneratedRelationMethods
      def sections: () -> ::ActiveSupport::HashWithIndifferentAccess[::String, ::String]

      def basic: () -> ::Copyright::Finding::ActiveRecord_Relation

      def not_basic: () -> ::Copyright::Finding::ActiveRecord_Relation

      def biographical: () -> ::Copyright::Finding::ActiveRecord_Relation

      def not_biographical: () -> ::Copyright::Finding::ActiveRecord_Relation

      def bibliographical: () -> ::Copyright::Finding::ActiveRecord_Relation

      def not_bibliographical: () -> ::Copyright::Finding::ActiveRecord_Relation

      def renewal: () -> ::Copyright::Finding::ActiveRecord_Relation

      def not_renewal: () -> ::Copyright::Finding::ActiveRecord_Relation
    end

    class ::Copyright::Finding::ActiveRecord_Relation < ::ActiveRecord::Relation
      include ::Enumerable[::Copyright::Finding]
      include ::Copyright::Finding::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Copyright::Finding, ::Integer]
    end

    class ::Copyright::Finding::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include ::Enumerable[::Copyright::Finding]
      include ::Copyright::Finding::GeneratedRelationMethods
      include ::ActiveRecord::Relation::Methods[::Copyright::Finding, ::Integer]

      def build: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::Finding
               | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::Finding]
      def create: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::Finding
                | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::Finding]
      def create!: (?::ActiveRecord::Associations::CollectionProxy::_EachPair attributes) ?{ () -> untyped } -> ::Copyright::Finding
                 | (::Array[::ActiveRecord::Associations::CollectionProxy::_EachPair] attributes) ?{ () -> untyped } -> ::Array[::Copyright::Finding]
      def reload: () -> ::Array[::Copyright::Finding]

      def replace: (::Array[::Copyright::Finding]) -> void
      def delete: (*::Copyright::Finding | ::Integer) -> ::Array[::Copyright::Finding]
      def destroy: (*::Copyright::Finding | ::Integer) -> ::Array[::Copyright::Finding]
      def <<: (*::Copyright::Finding | ::Array[::Copyright::Finding]) -> self
      def prepend: (*::Copyright::Finding | ::Array[::Copyright::Finding]) -> self
    end
  end
end

module ::Copyright
end
class ::ApplicationRecord < ::ActiveRecord::Base
end
class ::Copyright::Citation < ::ApplicationRecord
end
class ::Copyright::Citation::ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
end
class ::Copyright::Investigation < ::ApplicationRecord
end
